// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nolan.Infra.EfCore.PostGresSql;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Nolan.HK.Migrations.Migrations
{
    [DbContext(typeof(HomeWorkContext))]
    [Migration("20220620153803_c1")]
    partial class c1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Nolan.HK.Domain.Entities.TimeSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApproveStatus")
                        .HasColumnType("text");

                    b.Property<int>("ApproveStatusEnum")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ApproveTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TimeSheet");
                });

            modelBuilder.Entity("Nolan.HK.Domain.Entities.TimeSheetDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uuid")
                        .HasComment("项目id");

                    b.Property<int>("TimesheetCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimesheetID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Userid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TimeSheetDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
